chrome.runtime.onInstalled.addListener(() => {
  console.log('AI Live Translator extension installed');
  
  // Set default settings
  chrome.storage.sync.set({
    targetLanguage: 'en',
    autoDetect: true,
    llmProvider: 'openai',
    llmModel: 'gpt-3.5-turbo'
  });
});

// Handle side panel
chrome.sidePanel
  .setPanelBehavior({ openPanelOnActionClick: true })
  .catch((error) => console.error(error));

// Listen for messages from content script and side panel
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'translateText') {
    handleTranslation(message.text, message.options)
      .then(sendResponse)
      .catch((error) => sendResponse({ error: error.message }));
    return true;
  }
  
  if (message.action === 'summarizePage') {
    handleSummarization(message.content, message.targetLanguage)
      .then(sendResponse)
      .catch((error) => sendResponse({ error: error.message }));
    return true;
  }

  if (message.action === 'getPageContent') {
    getPageContent(sender.tab?.id)
      .then(sendResponse)
      .catch((error) => sendResponse({ error: error.message }));
    return true;
  }

  if (message.action === 'testLLMConnection') {
    testLLMConnection(message.config)
      .then(sendResponse)
      .catch((error) => sendResponse({ success: false, error: error.message }));
    return true;
  }
});

async function handleTranslation(text: string, options: any) {
  try {
    // Use Chrome's built-in translation API
    // Note: This is a simplified implementation - Chrome's translation API details may vary
    const result = await chrome.runtime.sendMessage({
      action: 'translate',
      text,
      targetLanguage: options.targetLanguage,
      sourceLanguage: options.sourceLanguage
    });
    
    return result;
  } catch (error) {
    console.error('Translation error:', error);
    throw error;
  }
}

async function handleSummarization(content: string, targetLanguage: string) {
  try {
    const settings = await chrome.storage.sync.get(['llmProvider', 'llmApiKey', 'llmModel']);
    
    if (!settings.llmApiKey) {
      throw new Error('LLM API key not configured. Please set it in the options page.');
    }

    // This would integrate with the actual LLM API
    // For now, return a placeholder
    return {
      summary: `Summary of the webpage content in ${targetLanguage}. (This would be generated by ${settings.llmProvider} ${settings.llmModel})`,
      wordCount: content.split(' ').length
    };
  } catch (error) {
    console.error('Summarization error:', error);
    throw error;
  }
}

async function getPageContent(tabId?: number) {
  if (!tabId) {
    throw new Error('No active tab found');
  }

  try {
    const results = await chrome.scripting.executeScript({
      target: { tabId },
      func: () => {
        return {
          title: document.title,
          content: document.body.innerText,
          url: window.location.href
        };
      }
    });

    return results[0]?.result;
  } catch (error) {
    console.error('Error getting page content:', error);
    throw error;
  }
}

async function testLLMConnection(config: any) {
  try {
    const testPrompt = 'Please respond with "Hello" to confirm the API connection is working.';
    
    let response;
    switch (config.provider) {
      case 'openai':
        response = await fetch('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${config.apiKey}`
          },
          body: JSON.stringify({
            model: config.model,
            messages: [{ role: 'user', content: testPrompt }],
            max_tokens: 10
          })
        });
        break;
        
      case 'gemini':
        response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${config.model}:generateContent?key=${config.apiKey}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: testPrompt }] }],
            generationConfig: { maxOutputTokens: 10 }
          })
        });
        break;
        
      case 'claude':
        response = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': config.apiKey,
            'anthropic-version': '2023-06-01'
          },
          body: JSON.stringify({
            model: config.model,
            max_tokens: 10,
            messages: [{ role: 'user', content: testPrompt }]
          })
        });
        break;
        
      default:
        throw new Error(`Unsupported provider: ${config.provider}`);
    }

    if (!response!.ok) {
      throw new Error(`API error: ${response!.status} ${response!.statusText}`);
    }

    return { success: true };
  } catch (error) {
    console.error('LLM connection test failed:', error);
    throw error;
  }
}